apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "preprocessing-service-terminology.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "preprocessing-service-terminology.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.config.environment | quote }}
  TERM_SERVER_URL: {{ .Values.config.termServerUrl | quote }}
  SERVER_PORT: "3000"
