apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "preprocessing-service-terminology.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "preprocessing-service-terminology.labels" . | nindent 4 }}
